default:
    tags:
      - jdk8 
image: $CI_REGISTRY/ops/qsc-maven:ali-v3
include:
  - project: 'opertations/gitlabci-templates'
    ref: main
    file: 
      - 'docker-login.yml'
      - 'maven-package.yaml'
      - 'k8s-build-image.yaml'

stages:
  - package
  - build-k8s-image

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

clean:
  stage: .pre
  script: mvn clean -U
  timeout: 1m
